# Generated by Django 2.1.7 on 2019-04-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, help_text='Write message for the user', max_length=300, verbose_name='Write message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Select a user, you want to play with', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recieved', to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
