# Generated by Django 2.2.1 on 2019-05-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
