# Generated by Django 2.2.1 on 2019-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190520_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_name',
            field=models.FileField(upload_to='profile_image/'),
        ),
    ]
