# Generated by Django 2.1.7 on 2019-04-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='by_first_player',
            new_name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_first_player',
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_second_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
