# Generated by Django 2.1.7 on 2019-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player Move'), ('S', 'Second player Move'), ('W', 'First player Win'), ('L', 'Second player Win'), ('D', 'Game draw')], default='F', max_length=1),
        ),
    ]
